// This file is automatically generated by vscode-react-native@0.3.2
// Please do not modify it manually. All changes will be lost.
var React = require('d:\dev\react-native-hello-world/node_modules/react');
var {Component} = React;

var ReactNative = require('d:\dev\react-native-hello-world/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('d:\dev\react-native-hello-world/index.android.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('hello-world', appParameters);
});